---
- name: Make sure home directory is owned by user
  file: path=/home/{{ socialhome_os_user }}/socialhome owner="{{ socialhome_os_user }}" group="{{ socialhome_os_user }}" recurse=yes state=directory
- name: Make sure venv directory is owned by user
  file: path=/home/{{ socialhome_os_user }}/venv owner="{{ socialhome_os_user }}" group="{{ socialhome_os_user }}" recurse=yes state=directory
- name: Get latest application code
  git: accept_hostkey=yes dest=/home/{{ socialhome_os_user }}/socialhome repo=https://github.com/jaywink/socialhome.git force=yes version=master
  become_user: "{{ socialhome_os_user }}"
  notify:
    - restart uwsgi
- name: Stop socialhome uWSGI
  service: name="{{ socialhome_domain }}" state=stopped
  notify:
    - restart uwsgi
- name: Install app OS requirements
  shell: chdir=/home/{{ socialhome_os_user }}/socialhome/ executable=/bin/bash ./install_os_dependencies.sh install
  notify:
    - restart uwsgi
- name: Install app requirements
  pip: requirements=/home/{{ socialhome_os_user }}/socialhome/requirements/production.txt virtualenv=/home/{{ socialhome_os_user }}/venv
  become_user: "{{ socialhome_os_user }}"
  notify:
    - restart uwsgi
- name: Ensure Social-Federation is upgraded
  pip: name='git+https://github.com/jaywink/social-federation.git@master#egg=Social-Federation' extra_args="-U" virtualenv=/home/{{ socialhome_os_user }}/venv
  become_user: "{{ socialhome_os_user }}"
  notify:
    - restart uwsgi
- name: Create env file
  template: dest=/home/{{ socialhome_os_user }}/socialhome/env.local src=env.local mode=0600
  become_user: "{{ socialhome_os_user }}"
  notify:
    - restart uwsgi
- name: Migrate db
  django_manage: app_path=/home/{{ socialhome_os_user }}/socialhome command="migrate --load-env" virtualenv=/home/{{ socialhome_os_user }}/venv
  become_user: "{{ socialhome_os_user }}"
  notify:
    - restart uwsgi

# Web stuff
- name: Do NPM install
  npm: path=/home/{{ socialhome_os_user }}/socialhome
  become_user: "{{ socialhome_os_user }}"
- name: Do bowering
  bower: path=/home/{{ socialhome_os_user }}/socialhome
  become_user: "{{ socialhome_os_user }}"
- name: Grunt things
  command: chdir=/home/{{ socialhome_os_user }}/socialhome ./node_modules/.bin/grunt build
  become_user: "{{ socialhome_os_user }}"

- name: Collect statics
  django_manage: app_path=/home/{{ socialhome_os_user }}/socialhome command="collectstatic --load-env --no-input" virtualenv=/home/{{ socialhome_os_user }}/venv
  become_user: "{{ socialhome_os_user }}"
  notify:
    - restart uwsgi
