---
- include: packages.yaml
- include: user.yaml
- include: uwsgi.yaml
- include: daphne.yaml
- include: channelworker.yaml
- include: apache.yaml
- include: postgresql.yaml
- include: python.yaml
- include: application.yaml
  environment:
    DJANGO_SETTINGS_MODULE: config.settings.production
- include: celery.yaml
