---
- include: packages.yaml
- include: user.yaml
- include: uwsgi.yaml
- include: apache.yaml
- include: postgresql.yaml
- include: python.yaml
  become_user: "{{ socialhome_os_user }}"
- include: circus.yaml
- include: application.yaml
  environment:
    DJANGO_SETTINGS_MODULE: config.settings.production
- include: circus_ini.yaml
- include: loggly.yaml
  when: socialhome_loggly
