---
- name: Ensure locales are set (LANGUAGE)
  lineinfile: line='LANGUAGE="{{ socialhome_locales }}"' dest=/etc/default/locale state=present
- name: Ensure locales are set (LC_ALL)
  lineinfile: line='LC_ALL="{{ socialhome_locales }}"' dest=/etc/default/locale state=present

- name: System dependencies
  apt:
    name: "{{ socialhome_system_dependencies }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Install postgres
  apt: name={{ socialhome_postgres_dependencies }} state=present
  when: socialhome_db_install_postgres
