---
- name: Create database
  postgresql_db: name={{ socialhome_db_name }}
  become_user: postgres
- name: Create user
  postgresql_user: db={{ socialhome_db_name }} name={{ socialhome_db_user }} password={{ socialhome_db_password }} priv=ALL
  become_user: postgres
- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{ socialhome_db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres

