---
- name: Update pip, setuptools and pip-tools
  pip:
    name:
    - pip
    - setuptools
    - pip-tools
    state: latest
    virtualenv: "/home/{{ socialhome_os_user }}/venv"
    virtualenv_python: python3
