---
- name: Socialhome user
  user: name="{{ socialhome_os_user }}" state=present
- name: Ensure www-data member of socialhome user group
  user: name=www-data append=yes groups="{{ socialhome_os_user }}" state=present
- name: Make socialhome user home non-world readable
  file: path=/home/{{ socialhome_os_user }} mode=0750 state=directory
- name: Ensure github.com is a known host
  lineinfile:
    dest: /home/{{ socialhome_os_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  become_user: "{{ socialhome_os_user }}"
